### ISSUE TITLE
Замечания по CopyFile

### ISSUE THREAD

**Issue by alexey-malov** [MaxMartST/OOP#1]
https://github.com/MaxMartST/OOP/blob/5e7eccdce265fef30a7b6542708a52d1d982c3f9/lab1/CopyFile/main.cpp#L32-L59

- [x] Выделить в отдельную функцию

**Comment by MaxMartST** [comment]
Вывел процесс копирования из inputFile в outputFile в отдельную функцию CopyFile

**Comment by alexey-malov** [comment]
https://github.com/MaxMartST/OOP/blob/887fd394d31cbe70708bee4ac9925734e581f833/Lw%201/lab1.1%20CopyFile/CopyFile/main.cpp#L35

- [ ] объекты следует передавать по константной ссылке, если функция не модифицирует их состояние.
Примитивные объекты передавать по константной ссылке выгоды нет, лучше по значению

**Comment by MaxMartST** [comment]
Исправил передачу объектов в функцию CopyFile по константной ссылке
